version: '2'
services:

#Je nach Leistung des Hostsystems kann es bis zu 2 Minuten dauern bis beim ersten Start alles eingerichtet ist.
#'docker logs $(docker ps | grep _nextcloud_1 | awk "{print \$1}")' zeigt:
#'SQLSTATE[HY000] [2002] Connection refused' solange bis die DB eingerichtet ist und:
#'Nextcloud is not installed' wenn Nextcloud eingerichtet wird und:
#'Command line: /usr/sbin/apache2 -D FOREGROUND' sobald Nextcloud läuft.

 nextcloud:
  image: eigenerserver/nextcloud:0.1.4
  restart: always
  links:
    - mariadb:mysql
    - redis:redis
  networks:
    - frontend
    - backend
  volumes:
    - ./nextcloud:/host/nextcloud
  environment:
    # Achtung bei Sonderzeichen im User / Passwort. Es sind nicht alle erlaubt.
    - NEXTCLOUD_DB_NAME=eigenerserverch
    - NEXTCLOUD_DB_USER=eigenerserverch
    - NEXTCLOUD_DB_PASSWORD=eigener-server.ch
    #- NEXTCLOUD_DOMAIN=eigener-server.ch
    - NEXTCLOUD_DOMAIN=192.168.1.97
    - NEXTCLOUD_ADMIN_PASSWORD=eigener-server.ch

 mariadb:
  image: eigenerserver/mariadb:0.1.0
  restart: always
  networks:
    - backend
  volumes:
    - ./mariadb:/host/mariadb
  environment:
    # Achtung bei Sonderzeichen im User / Passwort. Es sind nicht alle erlaubt.
    - MARIADB_DATABASE=eigenerserverch
    - MARIADB_USER=eigenerserverch
    - MARIADB_PASS=eigener-server.ch

 redis:
  image: eigenerserver/redis:0.1.0
  restart: always
  networks:
    - backend

 webserver:
  image: eigenerserver/apache2:0.1.2
  restart: always
  networks:
    - frontend
  volumes:
    - ./lektor/html:/var/www/html

 lektor:
  image: eigenerserver/lektor:0.1.0
  restart: always
  networks:
   - frontend
  volumes:
    - ./lektor:/host/lektor

 haproxy:
  image: eigenerserver/haproxy:0.1.4
  restart: always
  links:
    - nextcloud:nextcloud
    - webserver:webserver
    - lektor:lektor
  ports:
    - 80:80
    - 443:443
    - 1936:1936
    - 5000:5000
  networks:
    - frontend
  volumes:
    - ./haproxy:/host/haproxy
  environment:
    # Achtung bei Sonderzeichen im User / Passwort. Es sind nicht alle erlaubt.
    - HAPROXY_ADMIN_USER=admin
    - HAPROXY_ADMIN_PASSWORD=eigener-server.ch
    - HAPROXY_ADMIN_USER_IP=192.168.1.0/24

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge


