version: '2'
services:

# Hedgehog Cloud by www.eigener-server.ch https://www.eigener-server.ch/en/igel-cloud \
# is licensed under a Creative Commons Attribution 4.0 International Lizenz \
# http://creativecommons.org/licenses/by/4.0/ \
# To remove the links visit https://www.eigener-server.ch/en/igel-cloud"

# Depending on the system it could take up to two minutes until everything ist up. 
# 'docker logs $(docker ps | grep _nextcloud_1 | awk "{print \$1}")' shows:
# 'SQLSTATE[HY000] [2002] Connection refused' until mariadb is running
# 'Nextcloud is not installed' during the nextcloud setup
# 'Command line: /usr/sbin/apache2 -D FOREGROUND' after nextcloud is running

 nextcloud:
  image: eigenerserver/nextcloud:1.0
  restart: always
  links:
    - nextcloud_db:mysql
    - redis:redis
  networks:
    - frontend
    - backend
  volumes:
    - ./nextcloud:/host/nextcloud
  environment:
    # Achtung bei Sonderzeichen im User / Passwort. Es sind nicht alle erlaubt.
    - NEXTCLOUD_DB_NAME=eigenerserverch
    - NEXTCLOUD_DB_USER=eigenerserverch
    - NEXTCLOUD_DB_PASSWORD=eigener-server.ch
    #- NEXTCLOUD_DOMAIN=eigener-server.ch
    - NEXTCLOUD_DOMAIN=192.168.1.97
    - NEXTCLOUD_ADMIN_PASSWORD=eigener-server.ch

 nextcloud_db:
  image: eigenerserver/mariadb:1.0
  restart: always
  networks:
    - backend
  volumes:
    - ./nextcloud_db:/host/mariadb
  environment:
    # Achtung bei Sonderzeichen im User / Passwort. Es sind nicht alle erlaubt.
    - MARIADB_DATABASE=eigenerserverch
    - MARIADB_USER=eigenerserverch
    - MARIADB_PASS=eigener-server.ch

 redis:
  image: eigenerserver/redis:1.0
  restart: always
  networks:
    - backend

 ###################################################################
 # Lektor Webserver Version
 ###################################################################
 webserver:
  image: eigenerserver/apache2:1.0
  restart: always
  networks:
    - frontend
  volumes:
    - ./lektor/html:/var/www/html

 lektor:
  image: eigenerserver/lektor:1.0
  restart: always
  networks:
   - frontend
  volumes:
    - ./lektor:/host/lektor
 ###################################################################

 ###################################################################
 # Apache / PHP Webserver Version
 ###################################################################
 #webserver:
 # image: eigenerserver/apache2:1.0
 # restart: always
 # networks:
 #   - frontend
 # volumes:
 #   - ./webserver/html:/var/www/html
 ###################################################################

 ###################################################################
 # Wordpress Webserver Version
 ###################################################################
 #wordpress_db:
 # image: eigenerserver/mariadb:1.0
 # restart: always
 # networks:
 #   - backend_wordpress
 # volumes:
 #   - ./wordpress_db:/host/mariadb
 # environment:
 #   - MARIADB_DATABASE=wordpress
 #   - MARIADB_USER=eigenerserverch
 #   - MARIADB_PASS=eigener-server.ch
 #
 #webserver:
 # image: wordpress:4.7-php7.0-apache
 # restart: always
 # links:
 #   - wordpress_db:mysql
 # networks:
 #   - frontend
 #   - backend_wordpress
 # volumes:
 #   - ./wordpress:/var/www
 # environment:
 #  - WORDPRESS_DB_USER=eigenerserverch
 #  - WORDPRESS_DB_PASSWORD=eigener-server.ch
 #  - WORDPRESS_DB_NAME=wordpress
 ###################################################################

 letsencrypt:
  image: eigenerserver/letsencrypt:0.1
  restart: always
  networks:
    - frontend
  volumes:
    - ./letsencrypt:/etc/letsencrypt
    - ./haproxy/certs:/host/letsencrypt/certs/pem

 haproxy:
  image: eigenerserver/haproxy:1.0
  restart: always
  links:
    - nextcloud:nextcloud
    - webserver:webserver
    - letsencrypt:letsencrypt
    # The following link need to be removed if you don't use lektor
    - lektor:lektor
  ports:
    - 80:80
    - 443:443
    - 1936:1936
    - 5000:5000
  networks:
    - frontend
  volumes:
    - ./haproxy:/host/haproxy
  environment:
    # Achtung bei Sonderzeichen im User / Passwort. Es sind nicht alle erlaubt.
    - HAPROXY_ADMIN_USER=admin
    - HAPROXY_ADMIN_PASSWORD=eigener-server.ch
    - HAPROXY_ADMIN_USER_IP=192.168.1.0/24

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge


